name: Pull request check

on:
  pull_request:
    types: [opened, synchronize] # Workflow triggering events

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with: 
          node-version: '16'

      - name: Install dependencies
        run: |
          yarn
          yarn bootstrap

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build