name: Release!

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          yarn
          yarn bootstrap

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: remove .npmrc
        run: rm /home/runner/work/_temp/.npmrc

      - name: NPM release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish